# Generated by Django 2.2.4 on 2019-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
