# Generated by Django 2.2.4 on 2019-08-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190820_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Branch'),
        ),
    ]
